---
- name: be sure npt is installed
  apt: name=ntp state=present
  tags: ntp

- name: be sure nptd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp

- name: be sure git is installed
  apt: name=git state=present
  tags: git
